name: Deploy Lambda Functions

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Install zip utility
        run: sudo apt-get install zip -y

      - name: Package Lambda functions
        run: |
          mkdir -p Lib/terraform/lambda/packages
          for dir in Lib/lambdas/*; do
            name=$(basename "$dir")
            zip -j "Lib/terraform/lambda/packages/${name}.zip" "$dir/lambda.py"
          done

      - name: Terraform Init
        working-directory: Lib/terraform/lambda
        run: terraform init

      - name: Terraform Plan
        working-directory: Lib/terraform/lambda
        run: terraform plan -var-file="terraform.tfvars"

      - name: Terraform Apply
        working-directory: Lib/terraform/lambda
        run: terraform apply -auto-approve -var-file="terraform.tfvars"
